# FROM public.ecr.aws/lambda/nodejs:16 as builder
# WORKDIR /usr/app
# # A wildcard is used to ensure both package.json AND package-lock.json are copied 
# COPY package*.json ./ 
# COPY prisma ./prisma/ 
# # Install app dependencies 
# COPY . . 
# RUN npm install 
# RUN npm run build 
# RUN npm run schema:generate


# FROM public.ecr.aws/lambda/nodejs:16
# WORKDIR ${LAMBDA_TASK_ROOT}
# COPY --from=builder /usr/app/dist/* ./
# CMD ["dist/lambda.handler"]


FROM node:16 As builder 
# Create app directory 
WORKDIR /app 
# A wildcard is used to ensure both package.json AND package-lock.json are copied 
COPY package*.json ./ 
COPY prisma ./prisma/ 
# Install app dependencies 
COPY . . 
RUN npm install 
RUN npm run build 
RUN npm run schema:generate

EXPOSE 3000 
CMD [ "npm", "run", "start:prod" ]

