service: nest-lambda-docker

frameworkVersion: '3'

plugins:
  - serverless-jetpack
  # - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  stage: dev
  profile: lambda-docker
  ecr:
    images:
      appimage:
        path: ./

  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action: ["s3:*"]
          Resource:
            - "arn:aws:s3:::bucket/*"

functions:
  main:
    image:
      name: appimage
      command:
        - dist/lambda.handler
      entryPoint:
        - '/lambda-entrypoint.sh'
    # handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
