service: nestjs-serverless-pg

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  architecture: arm64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  memorySize: 128
  logRetentionInDays: 1
  timeout: 30

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true # This is required
    packager: 'npm'
    packagerOptions:
      scripts: # this is the magic
        - npx prisma generate

# custom:
#   esbuild:
#     bundle: true
#     minify: false
#     packager: 'npm'
#     external: 'node_modules'
#     # exclude: 'aws-sdk'
#     # target: node18.16.0
#     # define:
#     #   'require.resolve': undefined
#     # platform: node
#     # concurrency: 10
 

