export const MINIMUM_CLAIM_AMOUNT = 50000;
export const CC_TO_POUNDS_RATE = 10000;
export const REFERRAL_BONUS_PERCENTAGE = 0.1;
export const MINIMUM_STRIPE_AMOUNT_IN_PENCE = 100;
export const ANNUAL_SUBSCRIPTION_AMOUNT=29
export const ANNUAL_SUBSCRIPTION_RRP=14.50
export const ANNUAL_SUBSCRIPTION_DISCOUNT=65
